### ISSUE TITLE
Picodom→Ultradom

### ISSUE THREAD

**Issue by jorgebucaran** [brandonchartier/coppice#1]
Hi, @brandonchartier . 👋 

Just a friendly heads up! [Ultradom](https://github.com/jorgebucaran/ultradom) is the [continuation of and successor](https://github.com/jorgebucaran/ultradom/releases/tag/2.0.0) to Picodom. When you have time, could you please upgrade your package deps and add `ultradom` to your repo's tags?

**Comment by brandonchartier** [comment]
Hey, @jorgebucaran,

Thanks for the update. Hyperapp has added the state-last approach to updates that coppice was using, which is a great decision, along with many other nice features, since this was written. I have added deprecated warnings to npm and the README, since I have been working on a difference approach anyway.

Keep up the good work! :+1:
